services:
  db:
    image: postgres:latest
    container_name: my_postgres_container
    restart: always
    environment:
      POSTGRES_USER: APG
      POSTGRES_PASSWORD: 123ciao
      POSTGRES_DB: ProgCarc
    volumes:
      - ./internal/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./migration_add_livello.sql:/docker-entrypoint-initdb.d/migration_add_livello.sql
      - ./migration_add_iscrizioni.sql:/docker-entrypoint-initdb.d/migration_add_iscrizioni.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth-service:
    build: ./auth-service
    container_name: my_auth_service
    ports:
      - "8080:8080"  # Porta esposta per comunicare con il frontend
    environment:
      DB_HOST: db
      DB_USER: APG
      DB_PASSWORD: 123ciao
      DB_NAME: ProgCarc
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
    restart: always

  backend_python:
    build: ./backend_python
    container_name: my_backend_python
    ports:
      - "8000:8000"  # Porta esposta per comunicare con il frontend
    environment:
      DB_HOST: db
      DB_USER: APG
      DB_PASSWORD: 123ciao
      DB_NAME: ProgCarc
    depends_on:
      - db
    restart: always

volumes:
  pgdata: